services:
  caddy:
    image: caddy:2.10.2
    restart: unless-stopped
    networks:
      - edge
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:443:443/udp"
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  cloudflared:
    image: cloudflare/cloudflared:2025.11.1
    restart: unless-stopped
    depends_on:
      - caddy
    networks:
      - edge
    command:
      - tunnel
      - run
    volumes:
      - ./cloudflared-config.yaml:/etc/cloudflared/config.yml:ro
    environment:
      NO_AUTOUPDATE: "true"
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflare_token
    secrets:
      - cloudflare_token

networks:
  edge:
    name: edge

volumes:
  caddy_data:
  caddy_config:

secrets:
  cloudflare_token:
    file: ./cloudflare_token.secret
