services:
  db:
    image: postgres:18.1-alpine
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
    secrets:
      - postgres_passwd
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 10s
      timeout: 5s

volumes:
  pg-data:

secrets:
  postgres_passwd:
    file: ./postgres_passwd.secret
