---
- name: Dearmor Caddy repository signing key
  ansible.builtin.command:
    argv:
      - gpg
      - --dearmor
      - --yes
      - --output
      - "{{ caddy_gpg_key_path }}"
      - "{{ caddy_gpg_key_armored_path }}"
  changed_when: true

- name: Reload caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: reloaded
