services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:v1.14.1
    container_name: arcane
    restart: unless-stopped
    ports:
      - 3552:3552
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      ANALYTICS_DISABLED: "true"
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      UI_CONFIGURATION_DISABLED: "true"

volumes:
  arcane-data:
    driver: local
