---
- name: Update managed LXCs
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Bootstrap Python for Ansible if missing
      ansible.builtin.import_tasks: ../tasks/bootstrap-python.yaml

  tasks:
    - name: Upgrade installed packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        upgrade: full
        autoremove: true
