---
base_timezone: Etc/UTC
base_locale: en_GB.UTF-8
base_packages:
  - ca-certificates
  - curl
  - gnupg
  - locales
  - openssh-server
  - tzdata

base_admin_users: []
base_ssh_password_authentication: false
base_ssh_permit_root_login: prohibit-password
base_ssh_x11_forwarding: false
